module Rack
  module ICU4X
    class Locale
      VERSION: String
      ENV_KEY: String

      class Error < StandardError
      end

      type locale_input = String | ICU4X::Locale

      @app: _RackApp
      @from: Array[ICU4X::Locale]
      @cookie_name: String?
      @default: ICU4X::Locale?
      @negotiator: Negotiator

      def initialize: (
        _RackApp app,
        from: Array[locale_input],
        ?cookie: String?,
        ?default: locale_input?
      ) -> void
      def call: (Hash[String, untyped] env) -> [Integer, Hash[String, String], _ToA[String]]

      private

      def validate_default_in_from!: () -> void
      def detect_locales: (Hash[String, untyped] env) -> Array[ICU4X::Locale]
      def normalize_locale: (locale_input locale) -> ICU4X::Locale
      def cookie_locale: (Hash[String, untyped] env) -> Array[ICU4X::Locale]?
      def accept_language_locales: (Hash[String, untyped] env) -> Array[ICU4X::Locale]
      def parse_accept_language: (String header) -> Array[String]
      def parse_entry: (String part) -> [String, Float]
    end
  end
end

interface _RackApp
  def call: (Hash[String, untyped] env) -> [Integer, Hash[String, String], _ToA[String]]
end

interface _ToA[T]
  def to_a: () -> Array[T]
end
